<?xml version="1.0" encoding="utf-8"?><Database Name="PizzaHatDB" Class="LINQCajerosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=PizzaHatDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Evaluacion2NuevaNET.Properties.Settings" SettingsPropertyName="PizzaHatDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cajero" Member="Cajero">
    <Type Name="Cajero">
      <Column Name="rut" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>