<?xml version="1.0" encoding="utf-8"?><Database Name="PizzaHatDB" Class="LINQProductosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=PizzaHatDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Evaluacion2NuevaNET.Properties.Settings" SettingsPropertyName="PizzaHatDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>